In [27]:
from io import StringIO
import numpy as np
import pandas as pd

REAL_DATA = '''5,3,2,2,1,1,4,1,5,5,1,3,1,5,1,2,1,4,1,2,1,2,1,4,2,4,1,5,1,3,5,4,3,3,1,4,1,3,4,4,1,5,4,3,3,2,5,1,1,3,1,4,3,2,2,3,1,3,1,3,1,5,3,5,1,3,1,4,2,1,4,1,5,5,5,2,4,2,1,4,1,3,5,5,1,4,1,1,4,2,2,1,3,1,1,1,1,3,4,1,4,1,1,1,4,4,4,1,3,1,3,4,1,4,1,2,2,2,5,4,1,3,1,2,1,4,1,4,5,2,4,5,4,1,2,1,4,2,2,2,1,3,5,2,5,1,1,4,5,4,3,2,4,1,5,2,2,5,1,4,1,5,1,3,5,1,2,1,1,1,5,4,4,5,1,1,1,4,1,3,3,5,5,1,5,2,1,1,3,1,1,3,2,3,4,4,1,5,5,3,2,1,1,1,4,3,1,3,3,1,1,2,2,1,2,2,2,1,1,5,1,2,2,5,2,4,1,1,2,4,1,2,3,4,1,2,1,2,4,2,1,1,5,3,1,4,4,4,1,5,2,3,4,4,1,5,1,2,2,4,1,1,2,1,1,1,1,5,1,3,3,1,1,1,1,4,1,2,2,5,1,2,1,3,4,1,3,4,3,3,1,1,5,5,5,2,4,3,1,4
'''
real = np.bincount([int(x) for x in REAL_DATA.strip().split(',')], minlength=9)

df = pd.DataFrame([0,1,1,2,1,0,0,0,0], columns=['day1']).T
transitions_csv = '''0,1,0,0,0,0,0,0,0
0,0,1,0,0,0,0,0,0
0,0,0,1,0,0,0,0,0
0,0,0,0,1,0,0,0,0
0,0,0,0,0,1,0,0,0
0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,1,0
0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0
'''
transition_df = pd.read_csv(StringIO(transitions_csv), names=[f'from{i}' for i in range(9)])

In [28]:
real

array([  0, 109,  52,  43,  54,  42,   0,   0,   0])

In [40]:
(df.values @ np.linalg.matrix_power(transition_df.T.values, 256)).sum()

26984457539

In [39]:
(real @ np.linalg.matrix_power(transition_df.T.values, 256))

array([143504400459, 164841128531, 175950266416, 190070821679,
       215685790444, 220962408470, 259980229346, 119227821843,
       141425052085])

array([  0, 109,  52,  43,  54,  42,   0,   0,   0])

In [57]:
pd.Series.__matmul__??

In [64]:
real @ transition_df.T

0    109
1     52
2     43
3     54
4     42
5      0
6      0
7      0
8      0
dtype: int64

In [59]:
pd.Series(real).shape, transition_df.T.shape

((9,), (9, 9))

In [62]:
(pd.Series(real).T @ transition_df.T)#.values @ transition_df.T

ValueError: matrices are not aligned

In [66]:
pd.Series(real, index=transition_df.T.index) @ transition_df.T

0    109
1     52
2     43
3     54
4     42
5      0
6      0
7      0
8      0
dtype: int64

In [55]:
(pd.Series(real).values @ transition_df.T).values @ transition_df.T

0     52
1     43
2     54
3     42
4      0
5      0
6    109
7      0
8    109
dtype: int64

In [49]:
# day 2
(real @ transition_df.T)# @ transition_df.T

0    109
1     52
2     43
3     54
4     42
5      0
6      0
7      0
8      0
dtype: int64

In [38]:
(real & transition_df.T.values)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
transition_df.values @ transition_df.values

array([[0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
df.dot(transitions_csv)

IndexError: tuple index out of range

In [11]:
import numpy as np
np.linalg.matrix_power??